name: ci

on:
  pull_request:
    branches: [ main, master, "release/*" ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    uses: nikolareljin/ci-helpers/.github/workflows/python.yml@production
    with:
      working_directory: web-app
      lint_command: "python -m pip install -r requirements.txt && python -m pip install ruff && ruff check ."
      test_command: "echo 'No tests yet'"
